
# You can copy this Dockerfile.example to Dockerfile to add configuration
# or packages or anything else to your webimage
ARG BASE_IMAGE
FROM $BASE_IMAGE
#ADD laravel-worker.conf /etc/supervisor/conf.d
#ADD laravel-cron.conf /etc/supervisor/conf.d
